name: Build & Deploy Smart Tailor Application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.MY_APPLICATION }}:latest .

      - name: Push Docker Image to Docker Hub
        run: docker image push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.MY_APPLICATION }}:latest

#  deploy:
#    name: Deploy to Heroku
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Deploy to Heroku
#        uses: akhileshns/heroku-deploy@v3.13.15
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
#          heroku_email: ${{secrets.HEROKU_EMAIL}}

  deploy:
    name: Deploy to AWS EC2
    needs: build
    runs-on: [aws-ec2]

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Pull Docker Image From Docker Hub
        run: docker image pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.MY_APPLICATION }}:latest

      - name: Delete Old Docker Container
        run: docker container rm ${{ secrets.MY_APPLICATION }}

      - name: Run Docker Container
        run: |
          docker run --name ${{ secrets.MY_APPLICATION }} -p 6968:6969 \
            -e DBMS_CONNECTION=${{ secrets.DBMS_CONNECTION }} \
            -e DBMS_USERNAME=${{ secrets.DBMS_USERNAME }} \
            -e DBMS_PASSWORD=${{ secrets.DBMS_PASSWORD }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.MY_APPLICATION }}:latest
